title: 백시헌
description: > # this means to ignore newlines until "baseurl:"
  저를 소개하는 블로그입니다
baseurl: "/monday" # the subpath of your site, e.g. /blog
url: "https://github.com/bsh4090/bsh4090.github.io.git" # the base hostname & protocol for your site, e.g. 
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: 백시헌
tagline: 고등학생
about-description: # Add Discription
pic: 개.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: bsh3862@gmail.com # Add your Email address
phone: 010 4090 3862 # Add your Phone number
website: artemsheludko.pw # Add your website, do not add http://
github: bsh4090 # Add your Github handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
